// ============================================================
// FC Capacity & Inventory Planner — Dashboard Logic
// ============================================================
// This file loads JSON data generated by the Python planning
// engine and renders interactive charts, KPIs, a risk heatmap,
// and a sortable replenishment table.
// ============================================================

// ----- Global State -----
let currentScenario = 'BAU'; // 'BAU' or 'BBD'

// Raw data loaded from JSON files
let fcMaster = [];
let skuMaster = [];
let demandForecast = {};
let capacityAnalysis = {};
let stockoutRisk = {};
let replenishmentRecs = [];
let serviceLevels = {};

// Chart.js instances (stored so we can update/destroy them)
let fcUtilChart = null;
let demandChart = null;
let radarChartInstance = null;

// Table sort state
let sortColumn = 'days_of_supply';
let sortAscending = true;

// ============================================================
// 1. INITIALIZATION — runs when the page loads
// ============================================================
document.addEventListener('DOMContentLoaded', () => {
    setupScenarioToggle();
    setupTableSearch();
    setupTableSort();
    loadAllData();
});

// ============================================================
// 2. DATA LOADING — fetch all JSON files from data/ folder
// ============================================================
async function loadAllData() {
    try {
        // Fetch all 7 JSON files in parallel for speed
        const [fc, sku, demand, capacity, risk, recs, service] = await Promise.all([
            fetch('data/fc_master.json').then(r => { if (!r.ok) throw new Error(r.status); return r.json(); }),
            fetch('data/sku_master.json').then(r => { if (!r.ok) throw new Error(r.status); return r.json(); }),
            fetch('data/demand_forecast.json').then(r => { if (!r.ok) throw new Error(r.status); return r.json(); }),
            fetch('data/capacity_analysis.json').then(r => { if (!r.ok) throw new Error(r.status); return r.json(); }),
            fetch('data/stockout_risk.json').then(r => { if (!r.ok) throw new Error(r.status); return r.json(); }),
            fetch('data/replenishment_recs.json').then(r => { if (!r.ok) throw new Error(r.status); return r.json(); }),
            fetch('data/service_levels.json').then(r => { if (!r.ok) throw new Error(r.status); return r.json(); })
        ]);

        // Store in global variables
        fcMaster = fc;
        skuMaster = sku;
        demandForecast = demand;
        capacityAnalysis = capacity;
        stockoutRisk = risk;
        replenishmentRecs = recs;
        serviceLevels = service;

        // Hide error message if data loaded successfully
        document.getElementById('error-message').classList.add('hidden');

        // Render everything
        renderDashboard();

    } catch (error) {
        console.error('Failed to load data:', error);
        // Show helpful error message
        const errEl = document.getElementById('error-message');
        errEl.textContent = '⚠️ Could not load data files. Please run: python -m http.server 8000 in the fc-planner folder, then open http://localhost:8000';
        errEl.classList.remove('hidden');
    }
}

// ============================================================
// 3. SCENARIO TOGGLE — switch between BAU and BBD views
// ============================================================
function setupScenarioToggle() {
    const btnBAU = document.getElementById('btn-bau');
    const btnBBD = document.getElementById('btn-bbd');

    btnBAU.addEventListener('click', () => {
        if (currentScenario !== 'BAU') {
            currentScenario = 'BAU';
            btnBAU.classList.add('active');
            btnBBD.classList.remove('active');
            renderDashboard();
        }
    });

    btnBBD.addEventListener('click', () => {
        if (currentScenario !== 'BBD') {
            currentScenario = 'BBD';
            btnBBD.classList.add('active');
            btnBAU.classList.remove('active');
            renderDashboard();
        }
    });
}

// ============================================================
// 4. RENDER ALL — called on load and on scenario switch
// ============================================================
function renderDashboard() {
    renderKPIs();
    renderFCUtilChart();
    renderDemandChart();
    renderHeatmap();
    renderRadarChart();
    renderTable();
}

// ============================================================
// 5. KPI CARDS — animated counters at the top
// ============================================================
function renderKPIs() {
    const isBBD = currentScenario === 'BBD';

    // KPI 1: Total SKUs tracked
    animateCounter('kpi-skus', skuMaster.length);

    // KPI 2: Active Fulfilment Centers
    animateCounter('kpi-fcs', fcMaster.length);

    // KPI 3: Average Fill Rate
    // Use overall fill rate from service_levels.json
    const fillRate = isBBD
        ? serviceLevels.overall.fill_rate_bbd
        : serviceLevels.overall.fill_rate_bau;

    const fillEl = document.getElementById('kpi-fill-rate');
    animateCounter('kpi-fill-rate', fillRate, true);

    // Color code: green > 90%, amber > 80%, red < 80%
    if (fillRate > 90) fillEl.style.color = 'var(--accent)';
    else if (fillRate > 80) fillEl.style.color = 'var(--warning)';
    else fillEl.style.color = 'var(--danger)';

    // KPI 4: Stockout Alerts (count of High + Critical risk cells)
    const alertCount = stockoutRisk.matrix.filter(cell => {
        if (isBBD) {
            return cell.risk_level === 'Critical' || cell.risk_level === 'High';
        } else {
            return cell.risk_level === 'Critical';
        }
    }).length;
    animateCounter('kpi-alerts', alertCount);
}

/**
 * Smoothly animates a number from 0 to the target value.
 * Uses requestAnimationFrame for 60fps animation.
 */
function animateCounter(elementId, targetValue, isDecimal = false) {
    const element = document.getElementById(elementId);
    const duration = 1500; // 1.5 seconds
    let startTime = null;

    function step(timestamp) {
        if (!startTime) startTime = timestamp;
        const progress = Math.min((timestamp - startTime) / duration, 1);

        // Ease-out curve for smooth deceleration
        const easedProgress = 1 - Math.pow(1 - progress, 3);
        const currentValue = easedProgress * targetValue;

        if (isDecimal) {
            element.textContent = currentValue.toFixed(1) + '%';
        } else {
            element.textContent = Math.floor(currentValue).toLocaleString();
        }

        if (progress < 1) {
            requestAnimationFrame(step);
        } else {
            // Final value — ensure exact
            element.textContent = isDecimal
                ? targetValue.toFixed(1) + '%'
                : targetValue.toLocaleString();
        }
    }

    requestAnimationFrame(step);
}

// ============================================================
// 6. FC UTILIZATION CHART — horizontal bar chart
// ============================================================
function renderFCUtilChart() {
    const ctx = document.getElementById('fcUtilChart').getContext('2d');
    const isBBD = currentScenario === 'BBD';

    // Destroy previous chart if it exists
    if (fcUtilChart) fcUtilChart.destroy();

    // Extract data from capacity_analysis.json
    const fcData = capacityAnalysis.fc_utilization;
    const labels = fcData.map(fc => fc.name);
    const storageData = fcData.map(fc => isBBD ? fc.bbd_utilization_pct : fc.bau_utilization_pct);
    const throughputData = fcData.map(fc => isBBD ? fc.bbd_throughput_pct : fc.bau_throughput_pct);

    // Color bars based on utilization level
    // Green < 70%, Amber 70-90%, Red > 90%
    function getBarColor(value) {
        if (value > 90) return 'rgba(220, 38, 38, 0.8)';    // Red
        if (value > 70) return 'rgba(217, 119, 6, 0.8)';    // Amber
        return 'rgba(5, 150, 105, 0.8)';                     // Green
    }

    // Set Chart.js defaults for light theme
    Chart.defaults.color = '#64748b';
    Chart.defaults.font.family = 'Inter';

    fcUtilChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [
                {
                    label: 'Storage Utilization %',
                    data: storageData,
                    backgroundColor: storageData.map(getBarColor),
                    borderWidth: 1,
                    borderColor: 'rgba(0,0,0,0.05)',
                    borderRadius: 4
                },
                {
                    label: 'Throughput Utilization %',
                    data: throughputData,
                    backgroundColor: throughputData.map(getBarColor),
                    borderWidth: 1,
                    borderColor: 'rgba(0,0,0,0.05)',
                    borderRadius: 4
                }
            ]
        },
        options: {
            indexAxis: 'y',  // Horizontal bars
            responsive: true,
            maintainAspectRatio: false,
            scales: {
                x: {
                    max: 100,
                    grid: { color: 'rgba(0,0,0,0.06)' },
                    ticks: { callback: value => value + '%' }
                },
                y: { grid: { display: false } }
            },
            plugins: {
                legend: { position: 'top' },
                tooltip: {
                    callbacks: {
                        label: ctx => `${ctx.dataset.label}: ${ctx.raw.toFixed(1)}%`
                    }
                }
            }
        }
    });
}

// ============================================================
// 7. DEMAND FORECAST CHART — line chart over 90 days
// ============================================================
function renderDemandChart() {
    const ctx = document.getElementById('demandForecastChart').getContext('2d');
    const isBBD = currentScenario === 'BBD';

    if (demandChart) demandChart.destroy();

    // Format date labels (show only every 7th date for readability)
    const labels = demandForecast.dates.map(d => {
        const date = new Date(d);
        return date.toLocaleDateString('en-IN', { day: 'numeric', month: 'short' });
    });

    demandChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: labels,
            datasets: [
                {
                    label: 'BAU Demand',
                    data: demandForecast.bau_daily_demand,
                    borderColor: '#4f46e5',
                    backgroundColor: 'rgba(79, 70, 229, 0.08)',
                    borderWidth: 2,
                    tension: 0.4,
                    pointRadius: 0,
                    fill: true
                },
                {
                    label: 'BBD Peak Demand',
                    data: demandForecast.bbd_daily_demand,
                    borderColor: '#dc2626',
                    backgroundColor: 'rgba(220, 38, 38, 0.08)',
                    borderWidth: 2,
                    tension: 0.4,
                    pointRadius: 0,
                    fill: true,
                    hidden: !isBBD  // Only show BBD line in BBD mode
                }
            ]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            interaction: { mode: 'index', intersect: false },
            scales: {
                x: {
                    grid: { display: false },
                    ticks: { maxTicksLimit: 12 }
                },
                y: {
                    grid: { color: 'rgba(0,0,0,0.06)' },
                    ticks: { callback: value => value.toLocaleString() }
                }
            },
            plugins: {
                legend: { position: 'top' },
                tooltip: {
                    callbacks: {
                        label: ctx => `${ctx.dataset.label}: ${ctx.raw.toLocaleString()} units`
                    }
                }
            }
        }
    });
}

// ============================================================
// 8. STOCKOUT RISK HEATMAP — category × FC matrix
// ============================================================
function renderHeatmap() {
    const container = document.getElementById('heatmap-container');
    const isBBD = currentScenario === 'BBD';
    const matrix = stockoutRisk.matrix;

    // Extract unique categories and FCs (preserving order)
    const categories = [...new Set(matrix.map(cell => cell.category))];
    const fcs = [...new Set(matrix.map(cell => cell.fc_id))];
    const fcNames = {};
    matrix.forEach(cell => { fcNames[cell.fc_id] = cell.fc_name; });

    // Build lookup: category+fc_id -> cell data
    const lookup = {};
    matrix.forEach(cell => {
        lookup[cell.category + '|' + cell.fc_id] = cell;
    });

    // Color mapping based on risk level
    function getRiskColor(level) {
        switch (level) {
            case 'Critical': return '#dc2626';
            case 'High': return '#ef4444';
            case 'Medium': return '#f59e0b';
            case 'Low': return '#10b981';
            default: return '#6b7280';
        }
    }

    // Build HTML table
    let html = '<table class="heatmap-table">';

    // Header row with FC names
    html += '<tr><th>Category \\ FC</th>';
    fcs.forEach(fcId => {
        html += `<th>${fcNames[fcId]}</th>`;
    });
    html += '</tr>';

    // Data rows — one per category
    categories.forEach(cat => {
        html += `<tr><th>${cat}</th>`;
        fcs.forEach(fcId => {
            const cell = lookup[cat + '|' + fcId];
            if (cell) {
                const displayValue = isBBD
                    ? cell.days_of_supply_bbd
                    : cell.days_of_supply_bau;
                const riskColor = getRiskColor(cell.risk_level);
                const tooltip = `Risk: ${cell.risk_level}\nDOS (BAU): ${cell.days_of_supply_bau}\nDOS (BBD): ${cell.days_of_supply_bbd}\nAffected SKUs: ${cell.affected_skus}`;
                html += `<td class="heatmap-cell" style="background-color: ${riskColor}" data-tooltip="${tooltip}">${displayValue}d</td>`;
            } else {
                html += '<td>—</td>';
            }
        });
        html += '</tr>';
    });

    html += '</table>';
    container.innerHTML = html;

    // Attach JS tooltip to each heatmap cell (avoids CSS clipping issues)
    let tooltipEl = document.getElementById('heatmap-tooltip');
    if (!tooltipEl) {
        tooltipEl = document.createElement('div');
        tooltipEl.id = 'heatmap-tooltip';
        tooltipEl.className = 'tooltip';
        tooltipEl.style.display = 'none';
        document.body.appendChild(tooltipEl);
    }

    container.querySelectorAll('.heatmap-cell').forEach(cell => {
        cell.addEventListener('mouseenter', (e) => {
            tooltipEl.textContent = cell.getAttribute('data-tooltip');
            tooltipEl.style.display = 'block';
            const rect = cell.getBoundingClientRect();
            tooltipEl.style.left = (rect.left + rect.width / 2 - tooltipEl.offsetWidth / 2) + 'px';
            tooltipEl.style.top = (rect.top - tooltipEl.offsetHeight - 8) + 'px';
        });
        cell.addEventListener('mouseleave', () => {
            tooltipEl.style.display = 'none';
        });
    });
}

// ============================================================
// 9. SERVICE LEVEL RADAR CHART
// ============================================================
function renderRadarChart() {
    const ctx = document.getElementById('radarChart').getContext('2d');
    const isBBD = currentScenario === 'BBD';

    if (radarChartInstance) radarChartInstance.destroy();

    // Calculate average metrics across all FCs
    const metricKeys = ['availability', 'speed', 'cost_efficiency', 'capacity_headroom', 'stockout_resilience'];
    const metricLabels = ['Availability', 'Speed', 'Cost Efficiency', 'Capacity Headroom', 'Stockout Resilience'];

    const fcList = serviceLevels.by_fc;
    const bauValues = metricKeys.map(key => {
        const sum = fcList.reduce((acc, fc) => acc + fc.metrics[key].bau, 0);
        return Math.round(sum / fcList.length);
    });
    const bbdValues = metricKeys.map(key => {
        const sum = fcList.reduce((acc, fc) => acc + fc.metrics[key].bbd, 0);
        return Math.round(sum / fcList.length);
    });

    radarChartInstance = new Chart(ctx, {
        type: 'radar',
        data: {
            labels: metricLabels,
            datasets: [
                {
                    label: 'BAU',
                    data: bauValues,
                    backgroundColor: 'rgba(79, 70, 229, 0.15)',
                    borderColor: '#4f46e5',
                    pointBackgroundColor: '#4f46e5',
                    borderWidth: 2
                },
                {
                    label: 'BBD Peak',
                    data: bbdValues,
                    backgroundColor: 'rgba(220, 38, 38, 0.15)',
                    borderColor: '#dc2626',
                    pointBackgroundColor: '#dc2626',
                    borderWidth: 2,
                    hidden: !isBBD
                }
            ]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
                r: {
                    min: 0,
                    max: 100,
                    angleLines: { color: 'rgba(0,0,0,0.08)' },
                    grid: { color: 'rgba(0,0,0,0.08)' },
                    pointLabels: { color: '#475569', font: { size: 12, weight: 500 } },
                    ticks: { display: false }
                }
            },
            plugins: {
                legend: { position: 'top' }
            }
        }
    });
}

// ============================================================
// 10. REPLENISHMENT TABLE — sortable & filterable
// ============================================================
function setupTableSearch() {
    document.getElementById('table-search').addEventListener('input', renderTable);
}

function setupTableSort() {
    document.querySelectorAll('th[data-sort]').forEach(th => {
        th.addEventListener('click', () => {
            const col = th.getAttribute('data-sort');
            if (sortColumn === col) {
                sortAscending = !sortAscending;  // Toggle direction
            } else {
                sortColumn = col;
                sortAscending = true;
            }
            renderTable();
        });
    });
}

function renderTable() {
    const tbody = document.getElementById('table-body');
    const searchTerm = document.getElementById('table-search').value.toLowerCase();
    const isBBD = currentScenario === 'BBD';

    // Map raw data into display-friendly rows
    let rows = replenishmentRecs.map(rec => ({
        sku: rec.sku_id,
        name: rec.sku_name,
        category: rec.category,
        fc: rec.fc_name,
        stock: rec.current_stock,
        demand: isBBD ? rec.daily_demand_bbd : rec.daily_demand_bau,
        dos: rec.days_of_supply,
        reorder: rec.reorder_qty,
        priority: rec.priority,
        action: rec.action
    }));

    // Filter by search term
    if (searchTerm) {
        rows = rows.filter(r =>
            r.sku.toLowerCase().includes(searchTerm) ||
            r.name.toLowerCase().includes(searchTerm) ||
            r.category.toLowerCase().includes(searchTerm) ||
            r.fc.toLowerCase().includes(searchTerm)
        );
    }

    // Sort rows
    rows.sort((a, b) => {
        let valA, valB;

        // Map data-sort attribute to row field
        const fieldMap = {
            'sku': 'sku', 'name': 'name', 'category': 'category',
            'fc': 'fc', 'stock': 'stock', 'demand': 'demand',
            'dos': 'dos', 'reorder': 'reorder', 'priority': 'priority'
        };
        const field = fieldMap[sortColumn] || 'dos';
        valA = a[field];
        valB = b[field];

        // Custom sort for priority (Critical > Urgent > Monitor)
        if (sortColumn === 'priority') {
            const weights = { 'Critical': 3, 'Urgent': 2, 'Monitor': 1 };
            valA = weights[valA] || 0;
            valB = weights[valB] || 0;
        }

        if (valA < valB) return sortAscending ? -1 : 1;
        if (valA > valB) return sortAscending ? 1 : -1;
        return 0;
    });

    // Update item count
    document.getElementById('item-count').textContent = `${rows.length} items`;

    // Build table HTML
    tbody.innerHTML = '';
    rows.forEach(row => {
        const tr = document.createElement('tr');

        // Priority badge CSS class
        let priorityClass = 'priority-monitor';
        if (row.priority === 'Critical') priorityClass = 'priority-critical';
        else if (row.priority === 'Urgent') priorityClass = 'priority-urgent';

        tr.innerHTML = `
            <td>${row.sku}</td>
            <td>${row.name}</td>
            <td>${row.category}</td>
            <td>${row.fc}</td>
            <td>${row.stock.toLocaleString()}</td>
            <td>${row.demand.toFixed(1)}</td>
            <td>${row.dos.toFixed(1)}</td>
            <td>${row.reorder.toLocaleString()}</td>
            <td><span class="priority-badge ${priorityClass}">${row.priority}</span></td>
            <td>${row.action}</td>
        `;
        tbody.appendChild(tr);
    });

    // Update sort indicators in column headers
    document.querySelectorAll('th[data-sort] span').forEach(span => {
        span.textContent = '';
    });
    const activeHeader = document.querySelector(`th[data-sort="${sortColumn}"] span`);
    if (activeHeader) {
        activeHeader.textContent = sortAscending ? ' ↑' : ' ↓';
    }
}
